---
kind: pipeline
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init

- name: songbook
  image: alpine:3
  volumes:
    - name: tmp
      path: /tmp
  commands:
    - wget -O /tmp/Songbook.tar.gz https://src.mehl.mx/attachments/e4b9e058-ea5b-4964-bd22-d6cd18a2fd99
    - tar -xzf /tmp/Songbook.tar.gz -C /tmp
    # copy all songs and songbook pdf
    - mkdir static/songbook/
    - cp /tmp/Songs/* /tmp/Songbook.pdf static/songbook/
    # copy songbook.md
    - cp /tmp/songbook.md content/

- name: build
  image: monachus/hugo:v0.75.1
  environment:
    PIWIK_URL:
      from_secret: piwik_url
    PIWIK_TOKEN_AUTH:
      from_secret: piwik_token_auth
  commands:
  - sed -i -e "s|%PIWIK_URL%|$PIWIK_URL|" static/config.php
  - sed -i -e "s|%PIWIK_TOKEN_AUTH%|$PIWIK_TOKEN_AUTH|" static/config.php
  - hugo

- name: deploy
  image: appleboy/drone-scp
  settings:
    host:
      - pfadfinder-konstanz.de
    user: pfadiskn
    key:
      from_secret: ssh_key
    port: 22
    command_timeout: 2m
    target: /var/www/virtual/pfadiskn/html/
    source: public/*
    rm: true
    strip_components: 1

volumes:
- name: tmp
  temp: {}
