---
kind: pipeline
name: deployment
type: docker

platform:
  arch: amd64
  os: linux

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init

- name: build
  image: monachus/hugo:v0.75.1
  environment:
    PIWIK_URL:
      from_secret: piwik_url
    PIWIK_TOKEN_AUTH:
      from_secret: piwik_token_auth
  commands:
  - cp static/config.sample.php static/config.php
  - sed -i -e "s|%PIWIK_URL%|$PIWIK_URL|" static/config.php
  - sed -i -e "s|%PIWIK_TOKEN_AUTH%|$PIWIK_TOKEN_AUTH|" static/config.php
  - hugo

- name: deploy
  image: appleboy/drone-scp
  settings:
    host:
      - pfadfinder-konstanz.de
    user: pfadiskn
    key:
      from_secret: ssh_key
    port: 22
    command_timeout: 2m
    target: /var/www/virtual/pfadiskn/html/
    source: public/*
    rm: true
    strip_components: 1

volumes:
- name: tmp
  temp: {}
